### ISSUE TITLE
Benchmark an existing cluster

### ISSUE THREAD

**Issue by akshatgit** [openmessaging/benchmark#202]
Hi,

I am new to this tool, and I want to review an existing Kafka cluster. Is it possible to run the benchmark for an existing cluster without spawning a new one?

Thanks for the help!
Akshat

**Comment by himanshusagar** [comment]
I was searching on google for exactly this. I assume there must be some way to do this because open-benchmark has config files to deploy. We just need to find how they're being used and "hack" it for our own cluster.

https://github.com/openmessaging/benchmark/blob/4405623801e0b8869ab83e72a156d96dbbae04a9/driver-kafka/deploy/ssd-deployment/provision-kafka-aws.tf

**Comment by dave2wave** [comment]
The deploy script sets the client `driver-kafka/kafka*.yaml` files. You could eliminate the kafka cluster from the tf file and then edit your driver files on your deployed client before running:
```
cd /opt/benchmark
sudo vi driver-kafka/kafka-<d>.yaml
sudo bin/benchmark   --drivers driver-kafka/kafka-<d>.yaml   workloads/<w>.yaml
```

**Comment by akshatgit** [comment]
Thanks a lot, Dave! I figured it out using kafka.yaml
