### ISSUE TITLE
The deployments are varied

### ISSUE THREAD

**Issue by Hellojungle** [openmessaging/benchmark#78]
Currently, the deployments are different, for example the rabbitmq is one client and three broker while the rocketmq is four client and two broker. And what's more , rocketmq is deployed on alicloud. 
If we want to compare their performance, should it be a analogous deployment？

**Comment by vongosling** [comment]
Thanks @Hellojungle we will work to polish here

**Comment by revans2** [comment]
@vongosling 
I don't think you understand how **bad** this really is, because it impacts the credibility of the benchmark itself.

For Example:

This benchmark has gotten a decent amount of press primarily from a comparison of Kafka and Pulsar.  It has been published all over claiming that pulsar has 150% better throughput and 40% lower latency
https://www.businesswire.com/news/home/20180306005633/en/Apache-Pulsar-Outperforms-Apache-Kafka-2.5x-OpenMessaging

Even though the hardware may be the same between the kafka and pulsar deploys, Pulsar is configured to use both nvme devices in the i3.4xlarge instances it is running on while kafka is configured to only use one of them. So if the publicized test was run with the current code pulsar was able to get 150% better throughput with 200% more resources, which is a very different headline.

This really needs to be fixed if any of the results from this benchmark are to be trusted or compared with each other.

**Comment by merlimat** [comment]
@revans2 In BookKeeper case, the data is written to both NVMEs (one for journal and the other for storage). Kafka has no option to use multiple disks (sure, it couId be configured in raid-0) though in any case, for Kafka the disk was not the bottleneck of the benchmark.

**Comment by merlimat** [comment]
@revans2 In any case, it would be good for people more familiar with Kafka to validate deployment settings and API usage

**Comment by vongosling** [comment]
@revans2 Thanks for your advice. Benchmark nowadays has not been ready, the hint you could see from the latest pr. Fairness is something we value very much. I think our TSC member should not post unilateral hasty release of tendentious articles. Besides Kafka and Pulsar, we almost involved in most popular messaging, such as RabbitMQ, RocketMQ, NATS Streaming and NSQ. I think it not a good time to post any result in website consider there is much polishes for Benchmark @merlimat

**Comment by revans2** [comment]
@merlimat 

First off kafka does support multiple directories `log.dirs` is a comma-separated list of directories, just like `journalDirectories` and `ledgerDirectories` are in bookkeeper.  Kafka can only use them if there are enough partitions or topics to take advantage of them. [Several](https://github.com/openmessaging/openmessaging-benchmark/blob/master/workloads/1-topic-100-partitions-1kb.yaml) [tests](https://github.com/openmessaging/openmessaging-benchmark/blob/master/workloads/100-topics-1-partitions-1kb.yaml) in this repo do cover those situations.

I am not claiming that your results are wrong.  I have no idea if your results would be impacted by the change or not because I have not run the benchmark in both situations.  Even if the results would be absolutely identical benchmarks have a bad reputation right up there with [lies and statistics](https://en.wikipedia.org/wiki/Lies,_damned_lies,_and_statistics), which means you have to be very careful with perception if you want the benchmark to be taken seriously.  Having a lot of the benchmarks run out of the box on different hardware makes it difficult to make any kind of comparisons and hence lowers my trust of in the benchmark. Then when looking deeper at the tests that do run on the same hardware I see that some are configured to use less hardware makes me question why (especially if there is no documentation as to why) which again lowers my trust in the benchmark as a whole.  My point is that if you want this benchmark to be taken seriously you need to fix the problem of different hardware being used. 

I personally would argue that you want a single teraform configuration, and then a separate anseble for each of the drivers. 

@vongosling if the benchmark is not ready, then there needs to be documentation about that.  http://openmessaging.cloud/docs/benchmarks/ has no indication that I could find that it is not ready for prime time, or even that some of the drivers are more ready than others.  The only thing I could find on the github repo that indicates this is that there are no official releases, despite having widely publicised results from it.

**Comment by merlimat** [comment]
> First off kafka does support multiple directories log.dirs is a comma-separated list of directories, just like journalDirectories and ledgerDirectories are in bookkeeper. Kafka can only use them if there are enough partitions or topics to take advantage of them. Several tests in this repo do cover those situations.

Surely agree with that. The intention was always to give the most fair deployment scenarios and I 100% that it addition to "be" the same it also needs to "look" the same (to the max extent, given inherent differences between the different systems).

Just as side note (that doesn't change the above statement),  the reported results were only related to 1-topic-1-partition cases.

Created #125 . Again, it would be very very valuable if you could check the whole deployment settings and also the driver implementation.

> I personally would argue that you want a single teraform configuration, and then a separate anseble for each of the drivers.

Absolutely agree with that. There was an earlier effort in unifying that (when there were 2 drivers only for the benchmark), see #47 .

I think the biggest obstacle reside in that different systems will have different requirements. While that's not necessarily the case in Pulsar vs Kafka, it would be in other systems that for example don't rely on ZookKeeper.

Another issue was that I couldn't find a way to complete the formatting/mount/soft-raid operations from Terraform and just gave up and started doing that in Ansible, even though it would be logically more suited in the "infrastructure" side of things.
